services:
  dlstreamer:
    build:
      context: .
      dockerfile: Dockerfile
    image: tec/dlstreamer:devel
    ports:
      - "8888:8888"
    privileged: true
    network_mode: host
    working_dir: /home/dlstreamer
    command: /home/dlstreamer/.local/bin/jupyter-lab --no-browser --ip=0.0.0.0 --port=8888 --allow-root
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
      - .:/home/dlstreamer/dlstreamer_notebooks:rw
